web:
  build: .
  environment:
    - ENV=production
  ports:
    - "8001:8000"
  links:
    - db:db
  volumes:
    - .:/root/app
  restart: always
  command: 'python3 manage.py runserver 0.0.0.0:8000 -v 3'
db:
  image: postgres
  restart: always
  environment:
    - POSTGRES_PASSWORD=password
