web:
  build: .
  environment:
    - ENV=production
  ports:
    - "8001:8000"
  links:
    - db:postgres
  restart: always
  command: '2python3 manage.py runserver'
db:
  image: postgres
  restart: always
  environment:
    - POSTGRES_PASSWORD=password
