web:
  build: .
  environment:
    - ENV=production
  ports:
    - "8001:8000"
  links:
    - db:db
  volumes:
    - .:/root/app
  restart: always
db:
  image: postgres
  restart: always
  environment:
    - POSTGRES_PASSWORD=password
