web:
  build: .
  environment:
    - ENV=production
  ports:
    - "8001:80"
  links:
    - db:db
  restart: always
db:
  image: postgres
  restart: always
  environment:
    - POSTGRES_PASSWORD=password
