# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 16:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('goto', '0001_initial'), ('goto', '0002_auto_20160624_0829'), ('goto', '0003_auto_20160624_1647'), ('goto', '0004_auto_20160626_1309'), ('goto', '0005_auto_20160626_1630'), ('goto', '0006_auto_20160627_0940'), ('goto', '0007_auto_20160627_1201'), ('goto', '0008_gotouser_organization'), ('goto', '0009_auto_20160627_1242'), ('goto', '0010_auto_20160627_1728'), ('goto', '0011_auto_20160627_1729'), ('goto', '0012_auto_20160628_0735'), ('goto', '0013_auto_20160628_0738'), ('goto', '0014_auto_20160628_0740'), ('goto', '0015_auto_20160628_0742'), ('goto', '0016_auto_20160628_0744'), ('goto', '0017_auto_20160628_0745'), ('goto', '0018_auto_20160628_1004'), ('goto', '0019_auto_20160628_1126'), ('goto', '0020_auto_20160629_0710'), ('goto', '0021_auto_20160629_0951'), ('goto', '0022_auto_20160629_1022'), ('goto', '0023_auto_20160629_1228'), ('goto', '0024_auto_20160629_1228'), ('goto', '0025_auto_20160629_1239'), ('goto', '0026_auto_20160629_1519'), ('goto', '0027_auto_20160629_1519'), ('goto', '0028_auto_20160629_1549'), ('goto', '0029_auto_20160629_1553'), ('goto', '0030_auto_20160630_0740'), ('goto', '0031_participantcomment_project_projectcomment'), ('goto', '0032_auto_20160701_1134'), ('goto', '0033_auto_20160701_1142'), ('goto', '0034_auto_20160703_1714'), ('goto', '0035_auto_20160703_1848'), ('goto', '0036_auto_20160708_0838'), ('goto', '0037_auto_20160708_0920'), ('goto', '0038_auto_20160708_0921'), ('goto', '0039_auto_20160708_0921'), ('goto', '0040_auto_20160708_0933'), ('goto', '0041_auto_20160708_1006'), ('goto', '0042_auto_20160708_1007')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('admin', '0002_logentry_remove_auto_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teacher_images/')),
            ],
            options={
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('place_of_birth', models.CharField(blank=True, max_length=140, null=True)),
                ('city', models.CharField(blank=True, default='Москва', max_length=40)),
                ('citizenship', models.CharField(blank=True, default='Российская Федерация', max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('parents_phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('programming_languages', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('document', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('document_number', models.IntegerField(blank=True, null=True)),
                ('police_number', models.IntegerField(blank=True, null=True)),
                ('vk', models.URLField(blank=True, default='', max_length=240)),
                ('github', models.URLField(blank=True, default='', max_length=240)),
                ('health_issues', models.CharField(blank=True, default='Никаких', max_length=40)),
                ('experience', models.CharField(blank=True, default='', max_length=700)),
                ('about', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GotoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('surname', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='expert',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='expert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('gotouser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goto.GotoUser')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('goto.gotouser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='gotouser_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goto.GotoUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='gotouser_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goto.GotoUser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In review'), (1, 'Approved'), (2, 'Declined'), (3, 'Confirmed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2000)),
                ('begin_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('format', models.CharField(blank=True, default='', max_length=400)),
                ('place', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Experting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In discuss'), (1, 'Confirmed'), (2, 'Canceled')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='experting',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Expert'),
        ),
        migrations.AddField(
            model_name='event',
            name='experts',
            field=models.ManyToManyField(through='goto.Experting', to='goto.Expert'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='goto.Application', to='goto.Participant'),
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event'),
        ),
        migrations.AddField(
            model_name='application',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Participant'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='pages',
            field=models.ManyToManyField(blank=True, to='goto.Page'),
        ),
        migrations.RemoveField(
            model_name='expert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='teacher_image',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='about',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='github',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='vk',
        ),
        migrations.AddField(
            model_name='expert',
            name='position',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='github',
            field=models.URLField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/no-photo.jpg', upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='vk',
            field=models.URLField(blank=True, default='', max_length=240),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='document',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='parents_phone_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='police_number',
        ),
        migrations.AddField(
            model_name='gotouser',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "Can't say")], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='organization',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Question'),
        ),
        migrations.AddField(
            model_name='event',
            name='questions',
            field=models.ManyToManyField(blank=True, to='goto.Question'),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='goto.Application'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gotouser_ptr',
        ),
        migrations.AddField(
            model_name='participant',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 9, 51, 50, 243587, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='target_auditory',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='programming_languages',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='health_issues',
            field=models.TextField(blank=True, default='Никаких'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'In review'), (1, 'Approved'), (2, 'Declined'), (3, 'Confirmed'), (4, 'Unconfirmed')], default=0),
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': ('view_personal_data', 'Can view personal data'), 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидает рассмотрения'), (1, 'Одобрена'), (2, 'Отклонена'), (3, 'Подтверждена'), (4, 'Не подтверждена')], default=0),
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': (('view_personal_data', 'Can view personal data'),), 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=2016),
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='participant',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParticipantComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goto.Participant')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='left_participant_comments', to='goto.GotoUser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event')),
                ('maintainers', models.ManyToManyField(to='goto.Participant')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Project')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='left_project_comments', to='goto.GotoUser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'permissions': (('view_personal_data', 'Can view personal data'), ('leave_private_comments', 'Can leave private comments'), ('view_private_comment', 'Can view private comments')), 'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='project',
            name='maintainers',
            field=models.ManyToManyField(related_name='projects', to='goto.Participant'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='solutions/')),
                ('score', models.FloatField(default=0)),
                ('expert_private_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Assignment')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goto.Expert')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Participant')),
                ('date_posted', models.DateTimeField(default=None)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('participant_comment', models.CharField(blank=True, max_length=1000)),
                ('expert_public_comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterModelOptions(
            name='gotouser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='expert',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='gotouser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='gotouser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='gotouser',
            name='email_tmp',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='first_name_tmp',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gotouser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='last_name_tmp',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gotouser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
