# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teacher_images/')),
            ],
            options={
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('place_of_birth', models.CharField(blank=True, max_length=140, null=True)),
                ('city', models.CharField(blank=True, default='Москва', max_length=40)),
                ('citizenship', models.CharField(blank=True, default='Российская Федерация', max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('parents_phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('programming_languages', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('document', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('document_number', models.IntegerField(blank=True, null=True)),
                ('police_number', models.IntegerField(blank=True, null=True)),
                ('vk', models.URLField(blank=True, default='', max_length=240)),
                ('github', models.URLField(blank=True, default='', max_length=240)),
                ('health_issues', models.CharField(blank=True, default='Никаких', max_length=40)),
                ('experience', models.CharField(blank=True, default='', max_length=700)),
                ('about', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
