# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0002_auto_20160624_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In review'), (1, 'Approved'), (2, 'Declined'), (3, 'Confirmed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2000)),
                ('begin_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('format', models.CharField(blank=True, default='', max_length=400)),
                ('place', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Experting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In discuss'), (1, 'Confirmed'), (2, 'Canceled')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='experting',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Expert'),
        ),
        migrations.AddField(
            model_name='event',
            name='experts',
            field=models.ManyToManyField(through='goto.Experting', to='goto.Expert'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='goto.Application', to='goto.Participant'),
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event'),
        ),
        migrations.AddField(
            model_name='application',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Participant'),
        ),
    ]
