# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0004_auto_20160626_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='teacher_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='about',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='github',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='vk',
        ),
        migrations.AddField(
            model_name='expert',
            name='company',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='about',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='github',
            field=models.URLField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='vk',
            field=models.URLField(blank=True, default='', max_length=240),
        ),
    ]
