# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0005_auto_20160626_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='document',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='parents_phone_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='police_number',
        ),
        migrations.AddField(
            model_name='gotouser',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "Can't say")], default='M', max_length=2),
        ),
    ]
