# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0006_auto_20160627_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gotouser',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/no-photo.jpg', upload_to='media/profile_pictures/'),
        ),
    ]
