# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0007_auto_20160627_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotouser',
            name='organization',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
