# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0008_gotouser_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gotouser',
            name='organization',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
