# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0012_auto_20160628_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='goto.Event'),
        ),
    ]
