# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0014_auto_20160628_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ManyToManyField(related_name='questions', to='goto.Question'),
        ),
    ]
