# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0016_auto_20160628_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='question',
        ),
        migrations.AddField(
            model_name='event',
            name='questions',
            field=models.ManyToManyField(blank=True, to='goto.Question'),
        ),
    ]
