# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0018_auto_20160628_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='goto.Application'),
            preserve_default=False,
        ),
    ]
