# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('goto', '0019_auto_20160628_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='gotouser_ptr',
        ),
        migrations.AddField(
            model_name='participant',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
