# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0020_auto_20160629_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 9, 51, 50, 243587, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gotouser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/no-photo.jpg', upload_to='profile_pictures/'),
        ),
    ]
