# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0021_auto_20160629_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='target_auditory',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
