# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0022_auto_20160629_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='company',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='gotouser',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='programming_languages',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
