# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0023_auto_20160629_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='health_issues',
            field=models.TextField(blank=True, default='Никаких'),
        ),
    ]
