# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0024_auto_20160629_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'In review'), (1, 'Approved'), (2, 'Declined'), (3, 'Confirmed'), (4, 'Unconfirmed')], default=0),
        ),
    ]
