# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0025_auto_20160629_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': ('view_personal_data', 'Can view personal data'), 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидает рассмотрения'), (1, 'Одобрена'), (2, 'Отклонена'), (3, 'Подтверждена'), (4, 'Не подтверждена')], default=0),
        ),
    ]
