# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0031_participantcomment_project_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantcomment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='left_participant_comments', to='goto.GotoUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='left_project_comments', to='goto.GotoUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantcomment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goto.Participant'),
        ),
    ]
