# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0032_auto_20160701_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'permissions': (('view_personal_data', 'Can view personal data'), ('leave_private_comments', 'Can leave private comments'), ('view_private_comment', 'Can view private comments')), 'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
