# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0034_auto_20160703_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='maintainers',
            field=models.ManyToManyField(related_name='projects', to='goto.Participant'),
        ),
    ]
