# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0035_auto_20160703_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='solutions/')),
                ('score', models.FloatField(default=0)),
                ('expert_comment', models.CharField(max_length=1000)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Assignment')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Expert')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Participant')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
