# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0037_auto_20160708_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goto.Expert'),
        ),
    ]
