# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0038_auto_20160708_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='expert_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
