# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0039_auto_20160708_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='expert_comment',
            new_name='expert_private_comment',
        ),
        migrations.AddField(
            model_name='solution',
            name='expert_public_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
