# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goto', '0040_auto_20160708_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gotouser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='expert',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='gotouser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='gotouser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='gotouser',
            name='email_tmp',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gotouser',
            name='first_name_tmp',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gotouser',
            name='id_tmp',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gotouser',
            name='last_name_tmp',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gotouser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
