# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0041_auto_20160708_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gotouser',
            old_name='id_tmp',
            new_name='id',
        ),
    ]
