# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0041_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='_subscribed_to_email',
            field=models.BooleanField(default=False),
        ),
    ]
