# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0043_auto_20160710_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_command', models.ManyToManyField(to='goto.Expert')),
                ('about_us_partners', models.ManyToManyField(related_name='about_us_partners', to='goto.Partner')),
                ('index_partners', models.ManyToManyField(related_name='index_partners', to='goto.Partner')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(blank=True, choices=[('school', 'Школа'), ('hackathon', 'Хакатон'), ('lecture', 'Лекция'), ('other', 'Лекция')], max_length=400),
        ),
    ]
