# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0045_auto_20160715_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partners'),
        ),
    ]
