# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0046_auto_20160715_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='about_us_command',
            new_name='about_us_team',
        ),
    ]
