# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0047_auto_20160715_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='short_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
