# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0047_auto_20160710_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
