# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0048_auto_20160722_0909'),
        ('goto', '0052_gotouser_verified'),
    ]

    operations = [
    ]
