# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0053_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMediaArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(blank=True, choices=[('school', 'Школа'), ('hackathon', 'Хакатон'), ('lecture', 'Лекция'), ('other', 'Другое')], max_length=400),
        ),
    ]
