# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0054_auto_20160724_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='massmediaarticle',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
