# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0055_massmediaarticle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massmediaarticle',
            old_name='url',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='massmediaarticle',
            name='image',
            field=models.ImageField(upload_to='mm-pictures'),
        ),
    ]
