# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0056_auto_20160724_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='experts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='experting',
            name='event',
        ),
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goto.Arrangement'),
        ),
        migrations.AddField(
            model_name='departments',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='goto.Event'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='goto.Event'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='experts',
            field=models.ManyToManyField(through='goto.Experting', to='goto.Expert'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='participants',
            field=models.ManyToManyField(through='goto.Application', to='goto.Participant'),
        ),
        migrations.AddField(
            model_name='application',
            name='arrangement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goto.Arrangement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goto.Departments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experting',
            name='arrangement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goto.Arrangement'),
            preserve_default=False,
        ),
    ]
