# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0057_auto_20160731_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='current_left_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_1', to='goto.Event'),
        ),
        migrations.AddField(
            model_name='settings',
            name='current_right_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_2', to='goto.Event'),
        ),
    ]
