# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0058_auto_20160731_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments'),
        ),
    ]
