# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0060_auto_20160731_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(to='goto.Partner'),
        ),
    ]
