# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0061_event_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=1024)),
                ('question_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goto.GotoUser')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='questions',
            new_name='applier_questions',
        ),
        migrations.AddField(
            model_name='event',
            name='faquestions',
            field=models.ManyToManyField(to='goto.FAQuestion'),
        ),
    ]
