# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 21:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('goto', '0062_auto_20160731_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
