# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0063_event_main_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.AlterField(
            model_name='event',
            name='faquestions',
            field=models.ManyToManyField(blank=True, to='goto.FAQuestion'),
        ),
    ]
