# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0065_auto_20160801_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
