# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0066_auto_20160801_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gotouser',
            old_name='verified',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='expert',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='citizenship',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='graduation_year',
            field=models.IntegerField(blank=True),
        ),
    ]
