# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0067_settings_current_hackathon'),
        ('goto', '0068_auto_20160813_1227'),
    ]

    operations = [
    ]
