# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0069_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gotouser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='gotouser',
            name='vk',
        ),
    ]
