# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0070_auto_20160814_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='education_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='participant',
            name='education_type',
            field=models.CharField(choices=[('school', 'Школа'), ('university', 'ВУЗ'), ('other', 'Другое')], default='school', max_length=32),
        ),
        migrations.AddField(
            model_name='participant',
            name='education_years',
            field=models.IntegerField(default=11),
        ),
    ]
