# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0070_auto_20160814_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pricture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
