# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0071_auto_20160817_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['my_order', '-date_created']},
        ),
        migrations.AddField(
            model_name='application',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
