# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0071_project_pricture'),
        ('goto', '0071_auto_20160817_1252'),
    ]

    operations = [
    ]
