# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0072_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_us_partners',
            field=models.ManyToManyField(blank=True, related_name='_settings_about_us_partners_+', to='goto.Partner'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='goto.Event'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_left_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='goto.Event'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_right_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='goto.Event'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='index_partners',
            field=models.ManyToManyField(blank=True, related_name='_settings_index_partners_+', to='goto.Partner'),
        ),
    ]
