# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0073_auto_20160824_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='arrangement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='goto.Arrangement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='goto.Event'),
        ),
    ]
