# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0072_auto_20160819_0910'),
        ('goto', '0074_auto_20160824_1258'),
    ]

    operations = [
    ]
