# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0075_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='steps',
            field=models.ManyToManyField(related_name='events', to='goto.Step'),
        ),
    ]
