# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0076_auto_20160824_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='steps',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='goto.Step'),
        ),
    ]
