# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('goto', '0077_auto_20160824_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='events', to='goto.Step'),
        ),
    ]
