# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('goto', '0080_auto_20160824_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('admin_title', models.CharField(max_length=240)),
                ('design', models.CharField(choices=[('prizes', 'Призы'), ('result', 'Итоги'), ('requirements', 'Требования'), ('expectations', 'Ожидания')], max_length=240)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Event')),
            ],
        ),
        migrations.CreateModel(
            name='BlockEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=240)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goto.Block')),
                ('picture', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
        ),
    ]
