# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0081_block_blockentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='arrangement',
        ),
        migrations.AddField(
            model_name='day',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='goto.Block'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='goto.Event'),
        ),
        migrations.AlterField(
            model_name='blockentity',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='goto.Block'),
        ),
    ]
