# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0082_auto_20160828_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='design',
            field=models.CharField(choices=[('prizes', 'Призы'), ('result', 'Итоги'), ('requirements', 'Требования'), ('expectations', 'Ожидания'), ('timesheet', 'Расписание')], max_length=240),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
