# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goto', '0083_auto_20160828_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
